export const GAME_RULES = {
  uno: {
    name: 'UNO',
    emoji: '🃏',
    players: '2-10',
    summary: 'Be the first to empty your hand!',
    rules: [
      'Each player starts with 7 cards',
      'Match the top card by color or number',
      'Wild cards can be played anytime (pick a color)',
      'Skip ⊘ — next player loses their turn',
      'Reverse ⟳ — changes play direction',
      'Draw Two +2 — next player draws 2 and skips',
      'Wild Draw Four +4 — pick color + next draws 4',
      'Call UNO when you have 1 card left!',
      "Can't play? Draw a card from the pile",
    ],
  },
  ludo: {
    name: 'Ludo',
    emoji: '🎲',
    players: '2-10',
    summary: 'Race all 4 tokens to the finish!',
    rules: [
      'Roll a 6 to move a token out of home',
      'Move tokens clockwise around the board',
      'Land on opponent = send them home',
      'Safe squares protect from captures',
      'Roll a 6 = extra turn (3 in a row = skip)',
      'First to get all 4 tokens home wins',
      'Capturing gives an extra turn',
    ],
  },
  teenpatti: {
    name: 'Teen Patti',
    emoji: '🂡',
    players: '2-10',
    summary: 'Indian poker — bet blind or seen!',
    rules: [
      '3 cards dealt face-down to each player',
      'Play blind (no peeking) or see your cards',
      'Blind bets = 1x-2x current stake',
      'Seen bets = 2x-4x current stake',
      'Fold to give up, Show to compare hands',
      'Hand rankings (high to low):',
      '  Trail (three of a kind)',
      '  Pure Sequence (straight flush)',
      '  Sequence (straight)',
      '  Color (flush)',
      '  Pair',
      '  High Card',
      'Last player standing wins the pot!',
    ],
  },
  napoleon: {
    name: 'Napoleon (Cards)',
    emoji: '👑',
    players: '2-10',
    summary: 'Trick-taking: Napoleon + Ally vs the rest!',
    rules: [
      'Cards dealt evenly to all players',
      'Bidding: declare how many tricks you\'ll win + trump suit',
      'Highest bidder becomes Napoleon',
      'Napoleon names an ally card (holder is secret ally)',
      'Play tricks: must follow lead suit if possible',
      'Trump suit beats all other suits',
      'Napoleon\'s team needs to hit their bid to win',
      'If they fail, the opposing team wins',
    ],
  },
  explodingkittens: {
    name: 'Exploding Kittens',
    emoji: '🐱',
    players: '2-10',
    summary: 'Don\'t draw the bomb! Last one alive wins.',
    rules: [
      'Play cards from your hand (optional)',
      'Then draw 1 card from the deck (mandatory)',
      'Draw an Exploding Kitten 💣 = use Defuse or die',
      'Defuse 🔧 — disarm bomb, hide it back in deck',
      'Attack ⚔️ — skip your draw, next player takes 2 turns',
      'Skip 🚫 — end turn without drawing',
      'Favor 🎁 — force someone to give you a card',
      'Shuffle 🔀 — randomize the deck',
      'See Future 🔮 — peek at top 3 cards',
      'Cat pairs — play 2 matching cats to steal a card',
      'Last player alive wins!',
    ],
  },
  napoleonword: {
    name: 'Napoleon Word Game',
    emoji: '🔤',
    players: '3-10',
    summary: 'Give a name, others guess — who said what?',
    rules: [
      'Each round, a category is announced (e.g., "Movie star")',
      'Everyone secretly submits a name/word',
      'All answers are revealed anonymously & shuffled',
      'Players take turns guessing who wrote what',
      'Correct guess = +1 point, wrong = guesser loses turn',
      'If your answer is guessed, you\'re "caught"',
      'Bonus: the "Napoleon" (highest scorer) picks next category',
      'Most points after all rounds wins!',
    ],
  },
};

export const GAME_LIST = Object.entries(GAME_RULES).map(([key, val]) => ({ key, ...val }));
